apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'git@github.com:willyhutw/microlab.git'
      path: argocd/internal/kube-prometheus-stack
      targetRevision: HEAD
      helm:
        valueFiles:
          - values.yaml
        releaseName: kube-prometheus-stack
    - repoURL: 'git@github.com:willyhutw/microlab.git'
      path: argocd/internal/kube-prometheus-stack/resources
      targetRevision: HEAD
    - repoURL: 'git@github.com:willyhutw/microlab.git'
      path: argocd/internal/kube-prometheus-stack/dashboards
      targetRevision: HEAD
      helm:
        valueFiles:
          - values.yaml
        releaseName: grafana-dashboards
  destination:
    name: micro
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
