apiVersion: v2
name: kube-prometheus-stack
description: A Helm chart depends on kube-prometheus-stack.
type: application
version: 82.1.1
appVersion: 82.1.1
dependencies:
  - name: kube-prometheus-stack
    version: 82.1.1
    repository: https://prometheus-community.github.io/helm-charts
